name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }} for server
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      working-directory: ./server

    - name: Debug npm configuration for server
      run: |
        echo "NPM cache directory: $(npm config get cache)"
        ls -al /home/runner/.npm
      working-directory: ./server

    - name: Clear npm cache for server
      run: npm cache clean -f
      working-directory: ./server

    - run: npm install
      working-directory: ./server

    # Add any server-specific build and test commands here

    - name: Use Node.js ${{ matrix.node-version }} for client
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      working-directory: ./client

    - name: Debug npm configuration for client
      run: |
        echo "NPM cache directory: $(npm config get cache)"
        ls -al /home/runner/.npm
      working-directory: ./client

    - name: Clear npm cache for client
      run: npm cache clean -f
      working-directory: ./client

    - run: npm install
      working-directory: ./client

    # Add any client-specific build and test commands here
