name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Build and Test Server
      run: |
        cd server
        echo "NPM cache directory: $(npm config get cache)"
        ls -al /home/runner/.npm
        npm cache clean -f
        npm install
        # Add any server-specific build and test commands here

    - name: Build and Test Client
      run: |
        cd client
        echo "NPM cache directory: $(npm config get cache)"
        ls -al /home/runner/.npm
        npm cache clean -f
        npm install
        # Add any client-specific build and test commands here
